### ISSUE TITLE
write.gdx is not handling name with dot inside

### ISSUE THREAD

**Issue by lolow** [lolow/gdxtools#1]
if the name of a set is including a dot, then write.gdx won't work. Reason: the parameter statement in the temporary gams will have a wrong number of indexes, resulting in GAMS error $163

**Comment by jackjackk** [comment]
I have a similar problem with set elements with spaces or special characters. In general, to be safe, I would quote set elements with "" when writing them in the temporary gams file.

**Comment by lolow** [comment]
fixed by 185e14f066797ccb389bb265c273518769cfb8f2
