### ISSUE TITLE
DEBUG 00: findrc = 2 is unhandled

### ISSUE THREAD

**Issue by dngreer46** [lolow/gdxtools#12]
I've never encountered this error before and have no idea what's causing it. It occurs when using rgdx.param(), but only some of the time.

**Comment by lolow** [comment]
Hi,
can you provide a small example and your GAMS version (platform+number), so I can try to reproduce the error. I know that some version of GAMS are not well supported. For example, GAMS 25.0 produces some errors while GAMS 25.1 is OK.

**Comment by dngreer46** [comment]
Thank you, but I discovered this error was caused by a corrupted gdx file so all is good now.
