### ISSUE TITLE
Write empty set

### ISSUE THREAD

**Issue by Mastomaki** [lolow/gdxtools#9]
I could not figure out how to write an empty set such as SET myset1(\*,\*);

**Comment by lolow** [comment]
This is not possible for the moment. If you try to write an empty
data.frame, it raises an error as gdxtools expects nrows>0. I see if I can
fix this. Thanks for the report.

**Comment by Mastomaki** [comment]
Actually I now could accomplish this. Try

myset <- data.frame(set1=integer(0), set2=numeric(0))
write.gdx("test.gdx",sets=list(my1=myset))

I am not sure though how I can specify "\*" as the name for both master sets (set1 and set2).

**Comment by lolow** [comment]
Thanks! To get the "*", you can name the columns as "V1" and "V2".

myset <- data.frame(set1=integer(0), set2=numeric(0))
colnames(myset) <- c("V1","V2")
write.gdx("empty_set.gdx",sets=list(my1=myset))
